### ISSUE TITLE
Exception: Did not receive a state packet from the Tello

### ISSUE THREAD

**Issue by pbag47** [Archimonde666/Challenge-drone-EA#18]
By trying to connect to the real Tello (especially with the school PCs), a similar exception might occur.

```
[INFO] tello.py - 104 - Tello instance was initialized. Host: '192.168.10.1'. Port: '8889'.
[INFO] tello.py - 418 - Send command: 'command'
[INFO] tello.py - 443 - Response command: 'ok'
Traceback (most recent call last):
  File "c:../Documents/DroneProgram/test.py", line 17, in <module>
    me.connect()
  File "C:..\AppData\Local\Programs\Python\Python37\lib\site-packages\djitellopy\enforce_types.py", line 49, in wrapper
    return func(*args, **kwargs)
  File "C:..\AppData\Local\Programs\Python\Python37\lib\site-packages\djitellopy\tello.py", line 526, in connect
    raise Exception('Did not receive a state packet from the Tello')
Exception: Did not receive a state packet from the Tello}
```

**Comment by pbag47** [comment]
This exception is generally caused by the Firewall.
To fix this issue, you may want to change the settings of the Tello network to switch it from public network settings to private network settings. This does not require to have admin privileges and it somehow solves the problem.
